
services:
  nextjs:
    build:
      context: .
      args:
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
    image: galacticosvb-nextjs
    container_name: galacticosvb
    restart: unless-stopped
    env_file:
      - .env.local
    environment:
      - AUTH_TRUST_HOST=true
      - AUTH_URL=https://galacticosvb.it
      # Gallery sync options
      - ENABLE_GALLERY_SYNC_CRON=true
      - DETECT_GALLERY_FOLDERS_ON_STARTUP=false
      - SYNC_GALLERY_ON_STARTUP=false
      # Puppeteer config
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    networks:
      - nginx
    volumes:
      - ./src/data:/app/src/data

networks:
  nginx:
    name: nginx_network
    external: true
